### ISSUE TITLE
error happens when launching the app

### ISSUE THREAD

**Issue by harlanc** [vimeo/vimeo-depth-viewer#5]
dyld: Library not loaded: @rpath/libnanogui.dylib
  Referenced from: /Users/simon/Downloads/depth-viewer-0.0.1/Vimeo Depth Viewer
  Reason: image not found
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by medlmichael** [comment]
Having the same issue as above

Gilmore-MacBook:~ medlmichael$ /Users/medlmichael/Downloads/depth-viewer-0.0.1/Vimeo\ Depth\ Viewer ; exit;
dyld: Library not loaded: @rpath/libnanogui.dylib
  Referenced from: /Users/medlmichael/Downloads/depth-viewer-0.0.1/Vimeo Depth Viewer
  Reason: image not found
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.


Is there a dependency I'm missing?

Love the work you done and hoping to get this running.  I'm using the 415.

**Comment by juniorxsound** [comment]
Thanks for the feedback! Unfortunately, macOS has deprecated the OpenGL API in Mojave which causes a lot of dependencies to fail.

That said, I was able to get it working on my machine (MBP 10.14.3) by doing the following:
1. Clone the latest repo by using `git clone https://github.com/vimeo/vimeo-depth-viewer.git --recursive`
1. Go into the folder and create a build directory `cd vimeo-depth-viewer && mkdir build`
1. Go into the build folder and run CMake by doing `cd build && cmake ../`
1. After CMake successfully finishes you can run `make -j` and it should build the software from source
1. If everything went well (with a lot of warnings but still built) you should be able to run `./VimeoDepthViewer` and it would launch the software

Feel free to post whether that was successful or if new issues came up

**Comment by juniorxsound** [comment]
Sounds like this solves the issue but in case it doesn't feel free to re-open / open a new one
